"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "pt" | "en";

export const translations = {
  pt: {
    portfolioTitle: "Portfólio v1.0.0",
    subtitle: "Desenvolvedor Front-End",
    bio: "Sou aficionado em tecnologia no geral, desenvolvo interfaces que unem elegância e intuitividade, sendo modernas o bastante para impressionar mas simples o suficiente para desaparecer. Estou em constante evolução no aprendizado e aperfeiçoamento, buscando sempre melhorar performance, fluidez e com muita atenção a todos os detalhes, acredito que a melhor experiência é aquela onde o usuário nem percebe que está tendo !",
    ctaHire: "Contrate-me",
    ctaCV: "Baixar CV",
    dock: {
      home: "Home",
      about: "Sobre",
      skills: "Skills",
      projects: "Projetos",
      contact: "Contato",
      terminal: "Terminal",
      blog: "Blog",
    },
    terminal: {
      boot: [
        { kind: "input",  text: "whoami" },
        { kind: "output", text: "Leandro Dukievicz" },
        { kind: "input",  text: "cat sobre.txt" },
        { kind: "output", text: "Front End - Transformando cafeína em interfaces desde 2021" },
        { kind: "input",  text: "ls skills/" },
        { kind: "output", text: "React  Next.js  TypeScript  Figma  Node  ..." },
        { kind: "input",  text: "./status.sh" },
        { kind: "output", text: "● Disponível para projetos" },
      ],
      help: [
        "Comandos disponíveis:",
        "  home         → página inicial",
        "  cv           → baixar currículo",
        "  sobre        → página sobre mim",
        "  skills       → minhas habilidades",
        "  projetos     → meus projetos",
        "  contato      → entrar em contato",
        "  blog         → meu blog",
        "  arquitetura  → stack deste portfólio",
        "  hacker       → ativar tema hacker [em breve]",
        "  sudo hire-me → 👀",
        "  clear        → limpar terminal",
        "  exit / sair  → fechar terminal",
        "  help         → mostrar esta ajuda",
      ],
      cmdArquitetura: [
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        " STACK — Portfólio Cyber v1.0.0",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        " Framework   →  Next.js 15 (App Router)",
        " Linguagem   →  TypeScript",
        " Estilização →  Tailwind CSS v4",
        " Animação    →  GSAP  |  requestAnimationFrame",
        " Efeitos     →  SVG Filters  |  CSS Houdini",
        " Ícones      →  React Icons",
        " Confetti    →  canvas-confetti",
        " Imagens     →  Next/Image  |  WebP",
        " Deploy      →  Vercel",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      ],
      cmdDownloading: "Baixando currículo...",
      cmdOpening: (page: string) => `Abrindo ${page}...`,
      cmdVerifying: "Verificando credenciais...",
      cmdAccessGranted: "✔ Acesso concedido. Baixando currículo...",
      cmdNotFound: (cmd: string) => `comando não encontrado: ${cmd}. Digite 'help'.`,
      cmdHackerSoon: "⚠ Tema hacker em desenvolvimento...",
      cmdHackerWait: "Aguarde a próxima versão.",
      cmdGoodbye: "Até logo!",
      inputHint: "— digite",
      inputHintCmd: "help",
      inputHintSuffix: "para ver todos os comandos",
      header: "guest@portfolio ~ zsh",
      toast: "Permissão Autorizada !!",
      modalTitle: "Obrigado pelo download!",
      modalMessage: "Fico muito feliz com seu interesse.\nEstou à inteira disposição para conversarmos\npessoalmente — será um prazer!",
      modalClose: "Fechar",
    },
    greeting: {
      default: "Olá! Seja bem-vindo ao meu portfólio.",
      withLocation: (loc: string) => `Olá, visitante de ${loc}! Seja bem-vindo.`,
      clickToClose: "clique para fechar",
    },
    marquee: "Bem vindo ao meu portifólio | Leandro Dukievicz | Dev Front End \u00a0\u00a0\u00a0",
    sobre: {
      windowTitle: "sobre.txt — Leandro Dukievicz",
      heading: "Sobre",
      bio1: "Olá, é uma grande satisfação receber a sua visita, espero que esteja gostando da experiência de navegar neste portfólio — me custou algumas boas horas para juntar e sintetizar aqui o meu gosto pessoal e transferir um pouco do que eu sou e curto, além de muitos neurônios queimados no processo!",
      bio2: "Sou desenvolvedor Full Stack, porém meu foco maior é no front, atualmente em transição de carreira, situado em Maringá-PR.",
      bio3: "Esta minha trilha no desenvolvimento de software com certeza não é uma linha reta, eu passei boa parte da minha vida trabalhando no setor de vendas e atualmente trabalho como motorista de app. Com certeza essa bagagem adquirida ao longo dos anos me ajudou e me moldou pra ser como eu sou hoje, na forma como procuro encarar os problemas com uma visão de negócio um pouco mais aguçada, também tendo empatia pelo usuário, pois eu já tive a perspectiva de quem está do outro lado da tela.",
      stackIntro: "Hoje meu foco é em construir aplicações web completas:",
      stack: [
        { label: "Front-end", desc: "com React e Next.js para interfaces escaláveis, modernas, performáticas, responsivas, pensadas para uma excelente experiência do usuário." },
        { label: "Back-end", desc: "com Node.js / Express, para APIs robustas, eficientes e seguras." },
        { label: "Dados",    desc: "com PostgreSQL e MySQL para modelagem e consultas em projetos reais." },
      ],
      bio4: "Além do código, gosto de tocar guitarra, violão, contrabaixo nas horas vagas, e claro, um assíduo consumidor de café, cinema e literatura ( principalmente ficção científica e sci-fi ), assim continuo alimentando a minha criatividade!",
      bio5: "Se você precisa de uma pessoa persistente e que aprende rápido para a sua equipe,",
      bio5Highlight: "vamos trocar uma ideia!",
      timelineTitle: "Formação Acadêmica",
      timeline: [
        { date: "26 / JAN / 2024", title: "Bacharelado em Sistemas para Internet", sub: "Desenvolvimento Web Full Stack · Unicesumar" },
        { date: "27 / MAR / 2025", title: "Pós-Graduação lato sensu", sub: "Desenvolvimento de Sistemas em Python · Concluído" },
        { date: "01 / JUN / 2025 · CURSANDO", title: "Pós-Graduação lato sensu", sub: "Negócios Digitais e Inovação", badge: "Em andamento" },
        { date: "Idiomas", title: "Inglês", sub: "( básico · em evolução para intermediário )", detail: "Com ênfase em termos técnicos e vocabulário relacionado à programação. Suficiente para comunicação efetiva no ambiente de desenvolvimento de software." },
      ],
      available: "Disponível para projetos",
      badgeStart: "Início",
      badgeCompleted: "Conclusão",
      badgeInProgress: "Em andamento",
      progressLabel: "Progresso",
      scrollDown: "scroll down",
      scrollUp: "scroll up",
    },
    projects: {
      comingSoon: "Em Breve",
      ctaDetails: "Ver Detalhes",
      ctaProject: "Ver Projeto",
      items: [
        {
          title: "Electrum — E-commerce Front-end",
          subtitle: "Front-end",
          description: "Front-end de um e-commerce fictício de eletrônicos, desenvolvido com foco na prática de SASS com arquitetura modular. O projeto simula um fluxo real de desenvolvimento frontend, com a estilização dividida em 3 módulos.",
        },
        {
          title: "Artes Urbanas",
          subtitle: "Front-end",
          description: "Projeto Front end de um site temático de artes urbanas, desenvolvido como primeiro contato com bootstrap 5 via CDN, conceitos praticados: containers, grid, breakpoints, colunas, alinhamentos, offset, ordenação de elementos e ícones.",
        },
        {
          title: "iMovi Construtora — Site Institucional",
          subtitle: "Front-end",
          description: "Landing Page de uma construtora, desenvolvido para consolidar técnicas do Bootstrap, recursos: sliders, cards, ícones, svg e customização seguindo estrutura de site institucional moderno.",
        },
        {
          title: "Barber Shop — Institucional",
          subtitle: "Front-end",
          description: "Landing page completa de uma barbearia com visual escuro e elegante, apresenta todas as seções típicas de um negócio local: hero com horários e endereço, seção sobre com história da empresa, listagem de serviços, formulário de agendamento e galeria de fotos, rodapé com localização no mapa.",
        },
        { title: "", subtitle: "", description: "", soonLabel: "Dashboard de Controle" },
        { title: "", subtitle: "", description: "", soonLabel: "Blog" },
        { title: "", subtitle: "", description: "" },
        { title: "", subtitle: "", description: "" },
        { title: "", subtitle: "", description: "" },
      ],
    },
    skills: {
      windowTitle: "skills.txt — Leandro Dukievicz",
      hardSkills: "Hard Skills",
      softSkills: "Soft Skills",
      back: "← Voltar",
      principlesTitle: "Princípios de Engenharia",
      principlesHint: "ver →",
      categories: ["Linguagens", "Boas Práticas", "Frameworks & Libs", "Banco de Dados", "Ferramentas"],
      softSkillsData: [
        { label: "Resolução de problemas",  desc: "Analiso problemas, quebro em partes menores, assim consigo ser mais eficiente." },
        { label: "Pensamento analítico",    desc: "Avalio cenários técnicos, entendo impactos e tomo decisões bem fundamentadas." },
        { label: "Comunicação clara",       desc: "Explico ideias técnicas para devs, designers e não-técnicos com objetividade." },
        { label: "Trabalho em equipe",      desc: "Colaboro com devs, designers e PMs para construir soluções melhores juntos." },
        { label: "Aprendizado contínuo",    desc: "Tecnologia evolui rápido — busco constantemente aprender novas ferramentas e conceitos." },
        { label: "Adaptabilidade",          desc: "Me ajusto rapidamente a mudanças de projeto ou tecnologia sem perder qualidade." },
        { label: "Organização",             desc: "Gerencio tarefas, prioridades e prazos de forma eficiente e consistente." },
        { label: "Atenção aos detalhes",    desc: "Percebo pequenos problemas que impactam performance, usabilidade e qualidade do código." },
        { label: "Proatividade",            desc: "Identifico melhorias e ajo antes que problemas apareçam, sem precisar ser solicitado." },
        { label: "Pensamento crítico",      desc: "Questiono soluções, avalio alternativas e busco sempre a melhor abordagem técnica." },
        { label: "Gestão do tempo",         desc: "Entrego tarefas dentro do prazo mantendo alta qualidade e organização." },
        { label: "Inteligência emocional",  desc: "Lido com pressão e feedback de forma madura, equilibrada e construtiva." },
        { label: "Princípios de Engenharia", desc: "" },
      ],
      principles: [
        { title: "Performance primeiro",                    desc: "Interfaces devem ser rápidas e eficientes. Cada milissegundo impacta a experiência do usuário." },
        { title: "Simplicidade vence complexidade",         desc: "A melhor solução geralmente é a mais simples de entender e manter." },
        { title: "Código é comunicação",                    desc: "Código não deve apenas funcionar — ele precisa ser claro para outros desenvolvedores." },
        { title: "Experiência do usuário em primeiro lugar", desc: "Tecnologia só tem valor quando melhora a experiência de quem usa o produto." },
        { title: "Escalabilidade desde o início",           desc: "Aplicações devem ser estruturadas para crescer sem gerar dívida técnica." },
        { title: "Consistência visual e técnica",           desc: "Interfaces e padrões de código devem seguir uma lógica consistente." },
        { title: "Automação sempre que possível",           desc: "Ferramentas e processos automatizados aumentam a qualidade e reduzem erros." },
      ],
    },
  },
  en: {
    portfolioTitle: "Portfolio v1.0.0",
    subtitle: "Front-End Developer",
    bio: "I am passionate about Technology in general, constantly studying and advancing for continuous improvement in developing interfaces that are elegant, easy to use, intuitive, and highly modern. Always striving to deliver better performance, details, and fluidity — because I believe the best interfaces are those that disappear for the end user, leaving only the experience.",
    ctaHire: "Hire me",
    ctaCV: "Download CV",
    dock: {
      home: "Home",
      about: "About",
      skills: "Skills",
      projects: "Projects",
      contact: "Contact",
      terminal: "Terminal",
      blog: "Blog",
    },
    terminal: {
      boot: [
        { kind: "input",  text: "whoami" },
        { kind: "output", text: "Leandro Dukievicz" },
        { kind: "input",  text: "cat about.txt" },
        { kind: "output", text: "Front End - Turning caffeine into interfaces since 2021" },
        { kind: "input",  text: "ls skills/" },
        { kind: "output", text: "React  Next.js  TypeScript  Figma  Node  ..." },
        { kind: "input",  text: "./status.sh" },
        { kind: "output", text: "● Available for projects" },
      ],
      help: [
        "Available commands:",
        "  home         → home page",
        "  cv           → download resume",
        "  about        → about me page",
        "  skills       → my skills",
        "  projects     → my projects",
        "  contact      → get in touch",
        "  blog         → my blog",
        "  arquitetura  → this portfolio's stack",
        "  hacker       → enable hacker theme [coming soon]",
        "  sudo hire-me → 👀",
        "  clear        → clear terminal",
        "  exit / quit  → close terminal",
        "  help         → show this help",
      ],
      cmdArquitetura: [
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        " STACK — Cyber Portfolio v1.0.0",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        " Framework   →  Next.js 15 (App Router)",
        " Language    →  TypeScript",
        " Styling     →  Tailwind CSS v4",
        " Animation   →  GSAP  |  requestAnimationFrame",
        " Effects     →  SVG Filters  |  CSS Houdini",
        " Icons       →  React Icons",
        " Confetti    →  canvas-confetti",
        " Images      →  Next/Image  |  WebP",
        " Deploy      →  Vercel",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      ],
      cmdDownloading: "Downloading resume...",
      cmdOpening: (page: string) => `Opening ${page}...`,
      cmdVerifying: "Verifying credentials...",
      cmdAccessGranted: "✔ Access granted. Downloading resume...",
      cmdNotFound: (cmd: string) => `command not found: ${cmd}. Type 'help'.`,
      cmdHackerSoon: "⚠ Hacker theme in development...",
      cmdHackerWait: "Wait for the next version.",
      cmdGoodbye: "Goodbye!",
      inputHint: "— type",
      inputHintCmd: "help",
      inputHintSuffix: "to see all commands",
      header: "guest@portfolio ~ zsh",
      toast: "Access Granted !!",
      modalTitle: "Thanks for the download!",
      modalMessage: "I'm very glad for your interest.\nI'm fully available to chat\nin person — it will be a pleasure!",
      modalClose: "Close",
    },
    greeting: {
      default: "Hello! Welcome to my portfolio.",
      withLocation: (loc: string) => `Hello, visitor from ${loc}! Welcome.`,
      clickToClose: "click to close",
    },
    marquee: "Welcome to my portfolio | Leandro Dukievicz | Front End Dev \u00a0\u00a0\u00a0",
    sobre: {
      windowTitle: "about.txt — Leandro Dukievicz",
      heading: "About",
      bio1: "Hello, it's a great pleasure to have your visit — I hope you're enjoying the experience of navigating this portfolio. It cost me quite a few good hours to gather and synthesize my personal taste here and transfer a bit of who I am and what I enjoy, along with many neurons burned in the process!",
      bio2: "I'm a Full Stack developer, but my main focus is on the front end, currently in career transition, based in Maringá-PR.",
      bio3: "My path in software development is certainly not a straight line — I spent most of my life working in sales and currently work as a rideshare driver. This baggage acquired over the years has certainly helped shape who I am today, in the way I approach problems with a sharper business perspective, and also with empathy for the user, since I've had the perspective of someone on the other side of the screen.",
      stackIntro: "Today my focus is on building complete web applications:",
      stack: [
        { label: "Front-end", desc: "with React and Next.js for scalable, modern, performant, responsive interfaces designed for an excellent user experience." },
        { label: "Back-end", desc: "with Node.js / Express, for robust, efficient, and secure APIs." },
        { label: "Data",     desc: "with PostgreSQL and MySQL for modeling and queries in real projects." },
      ],
      bio4: "Besides coding, I enjoy playing guitar, acoustic guitar, and bass in my free time — and of course, I'm an avid coffee drinker, movie lover, and bookworm ( especially science fiction and sci-fi ), keeping my creativity alive!",
      bio5: "If you need a persistent person who learns fast for your team,",
      bio5Highlight: "let's talk!",
      timelineTitle: "Academic Background",
      timeline: [
        { date: "26 / JAN / 2024", title: "Bachelor's Degree in Internet Systems", sub: "Full Stack Web Development · Unicesumar" },
        { date: "27 / MAR / 2025", title: "Postgraduate lato sensu", sub: "Python Systems Development · Completed" },
        { date: "01 / JUN / 2025 · IN PROGRESS", title: "Postgraduate lato sensu", sub: "Digital Business and Innovation", badge: "In progress" },
        { date: "Languages", title: "English", sub: "( basic · evolving to intermediate )", detail: "With emphasis on technical terms and vocabulary related to programming. Sufficient for effective communication in the software development environment." },
      ],
      available: "Available for projects",
      badgeStart: "Start",
      badgeCompleted: "Completed",
      badgeInProgress: "In progress",
      progressLabel: "Progress",
      scrollDown: "scroll down",
      scrollUp: "scroll up",
    },
    projects: {
      comingSoon: "Coming Soon",
      ctaDetails: "View Details",
      ctaProject: "View Project",
      items: [
        {
          title: "Electrum — E-commerce Front-end",
          subtitle: "Front-end",
          description: "Front-end of a fictional electronics e-commerce, developed with a focus on practicing SASS with modular architecture. The project simulates a real frontend development workflow, with styling split into 3 modules.",
        },
        {
          title: "Urban Arts",
          subtitle: "Front-end",
          description: "Front-end project of an urban arts themed website, developed as a first contact with Bootstrap 5 via CDN. Concepts practiced: containers, grid, breakpoints, columns, alignments, offset, element ordering, and icons.",
        },
        {
          title: "iMovi Construction — Institutional Site",
          subtitle: "Front-end",
          description: "Landing Page for a construction company, developed to consolidate Bootstrap techniques. Features: sliders, cards, icons, svg and customization following a modern institutional site structure.",
        },
        {
          title: "Barber Shop — Institutional",
          subtitle: "Front-end",
          description: "Complete landing page for a barbershop with a dark and elegant look, featuring all typical sections of a local business: hero with hours and address, about section with company history, services listing, scheduling form, photo gallery, and footer with map location.",
        },
        { title: "", subtitle: "", description: "", soonLabel: "Control Dashboard" },
        { title: "", subtitle: "", description: "", soonLabel: "Blog" },
        { title: "", subtitle: "", description: "" },
        { title: "", subtitle: "", description: "" },
        { title: "", subtitle: "", description: "" },
      ],
    },
    skills: {
      windowTitle: "skills.txt — Leandro Dukievicz",
      hardSkills: "Hard Skills",
      softSkills: "Soft Skills",
      back: "← Back",
      principlesTitle: "Engineering Principles",
      principlesHint: "see →",
      categories: ["Languages", "Best Practices", "Frameworks & Libs", "Database", "Tools"],
      softSkillsData: [
        { label: "Problem Solving",         desc: "I analyze problems, break them into smaller parts, and work more efficiently." },
        { label: "Analytical Thinking",     desc: "I evaluate technical scenarios, understand impacts, and make well-founded decisions." },
        { label: "Clear Communication",     desc: "I explain technical ideas to devs, designers, and non-technical people objectively." },
        { label: "Teamwork",                desc: "I collaborate with devs, designers, and PMs to build better solutions together." },
        { label: "Continuous Learning",     desc: "Technology evolves fast — I constantly seek to learn new tools and concepts." },
        { label: "Adaptability",            desc: "I adjust quickly to project or technology changes without losing quality." },
        { label: "Organization",            desc: "I manage tasks, priorities, and deadlines efficiently and consistently." },
        { label: "Attention to Detail",     desc: "I notice small issues that impact performance, usability, and code quality." },
        { label: "Proactivity",             desc: "I identify improvements and act before problems arise, without being asked." },
        { label: "Critical Thinking",       desc: "I question solutions, evaluate alternatives, and always seek the best technical approach." },
        { label: "Time Management",         desc: "I deliver tasks on time while maintaining high quality and organization." },
        { label: "Emotional Intelligence",  desc: "I handle pressure and feedback in a mature, balanced, and constructive way." },
        { label: "Engineering Principles",  desc: "" },
      ],
      principles: [
        { title: "Performance First",                  desc: "Interfaces must be fast and efficient. Every millisecond impacts the user experience." },
        { title: "Simplicity Beats Complexity",        desc: "The best solution is usually the simplest to understand and maintain." },
        { title: "Code is Communication",              desc: "Code must not just work — it needs to be clear to other developers." },
        { title: "User Experience First",              desc: "Technology only has value when it improves the experience of those who use the product." },
        { title: "Scalability from the Start",         desc: "Applications must be structured to grow without creating technical debt." },
        { title: "Visual and Technical Consistency",   desc: "Interfaces and code patterns must follow a consistent logic." },
        { title: "Automate Whenever Possible",         desc: "Automated tools and processes increase quality and reduce errors." },
      ],
    },
  },
} as const;

interface LanguageCtx {
  lang: Lang;
  t: typeof translations["pt"];
  toggle: () => void;
}

const Ctx = createContext<LanguageCtx | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("pt");
  const toggle = () => setLang(l => (l === "pt" ? "en" : "pt"));

  return (
    <Ctx.Provider value={{ lang, t: translations[lang] as typeof translations["pt"], toggle }}>
      {children}
    </Ctx.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
